package com.starcolon.ml.domain

import org.apache.spark.sql.{Dataset, Row}
import org.apache.spark.sql.types.StructField

object StackOverflowTypes {

  case class Bio(
    respondent: Int, 
    prefessional: String, 
    country: String, 
    race: String, 
    university: String)
  
  case class Job(
    respondent: Int,
    employmentstatus: String, 
    companysize: String, 
    companytype: String, 
    yearscodedjob: Int,
    developertype: String,
    jobsatisfaction: String,
    salary: String,
    expectedsalary: String)

  case class Personality(
    respondent: Int,
    learningnewtech: String)

  val columns = Seq(
    "Respondent",
    "Professional",
    "ProgramHobby",
    "Country",
    "University",
    "EmploymentStatus",
    "FormalEducation",
    "MajorUndergrad",
    "HomeRemote",
    "CompanySize",
    "CompanyType",
    "YearsProgram",
    "YearsCodedJob",
    "YearsCodedJobPast",
    "DeveloperType",
    "WebDeveloperType",
    "MobileDeveloperType",
    "NonDeveloperType",
    "CareerSatisfaction",
    "JobSatisfaction",
    "ExCoderReturn",
    "ExCoderNotForMe",
    "ExCoderBalance",
    "ExCoder10Years",
    "ExCoderBelonged",
    "ExCoderSkills",
    "ExCoderWillNotCode",
    "ExCoderActive",
    "PronounceGIF",
    "ProblemSolving",
    "BuildingThings",
    "LearningNewTech",
    "BoringDetails",
    "JobSecurity",
    "DiversityImportant",
    "AnnoyingUI",
    "FriendsDevelopers",
    "RightWrongWay",
    "UnderstandComputers",
    "SeriousWork",
    "InvestTimeTools",
    "WorkPayCare",
    "KinshipDevelopers",
    "ChallengeMyself",
    "CompetePeers",
    "ChangeWorld",
    "JobSeekingStatus",
    "HoursPerWeek",
    "LastNewJob",
    "AssessJobIndustry",
    "AssessJobRole",
    "AssessJobExp",
    "AssessJobDept",
    "AssessJobTech",
    "AssessJobProjects",
    "AssessJobCompensation",
    "AssessJobOffice",
    "AssessJobCommute",
    "AssessJobRemote",
    "AssessJobLeaders",
    "AssessJobProfDevel",
    "AssessJobDiversity",
    "AssessJobProduct",
    "AssessJobFinances",
    "ImportantBenefits",
    "ClickyKeys",
    "JobProfile",
    "ResumePrompted",
    "LearnedHiring",
    "ImportantHiringAlgorithms",
    "ImportantHiringTechExp",
    "ImportantHiringCommunication",
    "ImportantHiringOpenSource",
    "ImportantHiringPMExp",
    "ImportantHiringCompanies",
    "ImportantHiringTitles",
    "ImportantHiringEducation",
    "ImportantHiringRep",
    "ImportantHiringGettingThingsDone",
    "Currency",
    "Overpaid",
    "TabsSpaces",
    "EducationImportant",
    "EducationTypes",
    "SelfTaughtTypes",
    "TimeAfterBootcamp",
    "CousinEducation",
    "WorkStart",
    "HaveWorkedLanguage",
    "WantWorkLanguage",
    "HaveWorkedFramework",
    "WantWorkFramework",
    "HaveWorkedDatabase",
    "WantWorkDatabase",
    "HaveWorkedPlatform",
    "WantWorkPlatform",
    "IDE",
    "AuditoryEnvironment",
    "Methodology",
    "VersionControl",
    "CheckInCode",
    "ShipIt",
    "OtherPeoplesCode",
    "ProjectManagement",
    "EnjoyDebugging",
    "InTheZone",
    "DifficultCommunication",
    "CollaborateRemote",
    "MetricAssess",
    "EquipmentSatisfiedMonitors",
    "EquipmentSatisfiedCPU",
    "EquipmentSatisfiedRAM",
    "EquipmentSatisfiedStorage",
    "EquipmentSatisfiedRW",
    "InfluenceInternet",
    "InfluenceWorkstation",
    "InfluenceHardware",
    "InfluenceServers",
    "InfluenceTechStack",
    "InfluenceDeptTech",
    "InfluenceVizTools",
    "InfluenceDatabase",
    "InfluenceCloud",
    "InfluenceConsultants",
    "InfluenceRecruitment",
    "InfluenceCommunication",
    "StackOverflowDescribes",
    "StackOverflowSatisfaction",
    "StackOverflowDevices",
    "StackOverflowFoundAnswer",
    "StackOverflowCopiedCode",
    "StackOverflowJobListing",
    "StackOverflowCompanyPage",
    "StackOverflowJobSearch",
    "StackOverflowNewQuestion",
    "StackOverflowAnswer",
    "StackOverflowMetaChat",
    "StackOverflowAdsRelevant",
    "StackOverflowAdsDistracting",
    "StackOverflowModeration",
    "StackOverflowCommunity",
    "StackOverflowHelpful",
    "StackOverflowBetter",
    "StackOverflowWhatDo",
    "StackOverflowMakeMoney",
    "Gender",
    "HighestEducationParents",
    "Race",
    "SurveyLong",
    "QuestionsInteresting",
    "QuestionsConfusing",
    "InterestedAnswers",
    "Salary",
    "ExpectedSalary"
  )
}